all: application.css palettes.css pygments.css font-awesome.css

application.css: application-max.css
	cleancss -o application.css application-max.css

palettes.css: palettes-max.css
	cleancss -o palettes.css palettes-max.css

pygments.css: pygments-max.css
	cleancss -o pygments.css pygments-max.css

font-awesome.css: font-awesome-max.css
	cleancss -o font-awesome.css font-awesome-max.css


