baseurl = "https://pages.github.ibm.com/nanjj/go"
languageCode = "en-us"
title = "Go Learning"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
pygmentsstyle = "emacs"
pygmentscodefences = true
publishdir="."
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""
disableKinds=["404","RSS","sitemap"]

[params]
	# General information
	description = "Genesis Learning"
	copyright = "Released under the MIT license"

	# Repository
	repo_url = "https://github.ibm.com/nanjj/go"
    repo_branch = "gh-pages"
	logo = "images/logo.png"
	favicon = "images/favicon.png"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "blue-grey"
    	accent  = "teal"

    [params.font]
    	text = "Roboto"
    	code = "Roboto Mono"


[social]
	twitter = ""
	github  = ""
	email   = "nanjj@cn.ibm.com"


[[menu.main]]
	name   = "Go"
	url    = "/"
	weight = 10

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
